alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
functions:
- github:
    branch: main
    repo: abapPM/tools.abappm.com
  name: tools-api
  source_dir: /
ingress:
  rules:
  - component:
      name: tools-web
    match:
      path:
        prefix: /
  - component:
      name: tools-api
    match:
      path:
        prefix: /api
name: tools-abappm-com
region: fra
static_sites:
- environment_slug: html
  github:
    branch: main
    repo: abapPM/tools.abappm.com
  name: tools-web
  source_dir: web
